const ARTICLES_VIEW = 'ARTICLES_VIEW';
const CHANNELS_VIEW = 'CHANNELS_VIEW';
const ERROR_VIEW = 'ERROR_VIEW';
const INITIAL_VIEW = 'INITIAL_VIEW';
const MAIN_VIEW = 'MAIN_VIEW';

export {
    ARTICLES_VIEW,
    CHANNELS_VIEW,
    ERROR_VIEW,
    INITIAL_VIEW,
    MAIN_VIEW,
};